name: mediconnect
region: nyc
services:
  - name: mediconnect-backend
    github:
      repo: latifox/mediconnect_app
      branch: main
      deploy_on_push: true
    source_dir: mediconnect-backend
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    envs:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
        scope: RUN_TIME
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
        scope: RUN_TIME
      - key: JWT_EXPIRATION
        value: "86400000"
        scope: RUN_TIME
      - key: JWT_SECRET
        value: "${JWT_SECRET}"
        scope: RUN_TIME
        type: SECRET
      - key: SPRING_DATASOURCE_URL
        value: "${db.DATABASE_URL}"
        scope: RUN_TIME
      - key: SPRING_DATASOURCE_USERNAME
        value: "${db.USERNAME}"
        scope: RUN_TIME
      - key: SPRING_DATASOURCE_PASSWORD
        value: "${db.PASSWORD}"
        scope: RUN_TIME

  - name: mediconnect-frontend
    github:
      repo: latifox/mediconnect_app
      branch: main
      deploy_on_push: true
    source_dir: mediconnect-frontend
    dockerfile_path: Dockerfile
    http_port: 19000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: API_URL
        value: "${APP_URL}/api"
        scope: RUN_TIME
      - key: NODE_ENV
        value: production
        scope: RUN_TIME

databases:
  - name: mediconnect-db
    engine: PG
    version: "14"
    production: false
    db_name: mediconnect
    db_user: mediconnect 